### ISSUE TITLE
favicon not working

### ISSUE THREAD

**Issue by gedw99** [J-Siu/go-png2ico#6]
Hey @J-Siu 

I am converting a .png to an .ico

then renaming it to favicon.ico and using it in an index.html

<link rel="icon" type="image/x-icon" href="favicon.ico">

its not working.

SO i downloaded a favicon from the internet that does work, and then opened them both on my mac 

Top one is the one i converted with go-png2ico.
Bottom one is the one downloaded from the internet.

<img width="1280" alt="Screenshot 2023-04-25 at 12 00 31" src="https://user-images.githubusercontent.com/53147028/234243296-c2593487-d11a-4cf1-9488-418aedd91146.png">

It seems they are not both the same file types, because the OS treats them differently.
This is probably why a browser does not work with the top one too...

any ideas ??

**Comment by gedw99** [comment]
I messed around using png for web and it works fine with a web manifest on chrome and safari. No ico use.

But it would be good if ICO worked, so would still like to get to the bottom of this.

**Comment by gedw99** [comment]
of course.

The original PNG.
![logo](https://user-images.githubusercontent.com/53147028/234312281-905ffa8a-9915-49de-8421-ad4709294ffc.png)

Github does not allow me to upload a .ico file. so can upload the output, but easy for you to do it.

I also wanted to ad a .ico file that is one that works for an internet favicon. But again i cant upload it.
This is where i got mine: https://www.freefavicon.com/freefavicons/icons/downloadicon.php?ico=basketball-icon-89155.zip

**Comment by J-Siu** [comment]
Seems both Firefox and Chrome cannot handle ico with png > 256px.

I use ImageMagick `identify` to check the converted files info and they are correct:

```
$ identify test*
test-1200.ico PNG 1200x900 1200x900+0+0 8-bit sRGB 73432B 0.000u 0:00.000
test-1200.png PNG 1200x900 1200x900+0+0 8-bit sRGB 73410B 0.000u 0:00.000
test-256.ico PNG 256x192 256x192+0+0 8-bit sRGB 21473B 0.000u 0:00.000
test-256.png PNG 256x192 256x192+0+0 8-bit sRGB 21451B 0.000u 0:00.000
```

However test-1200.ico cannot be displayed by both browsers.

[test-256.ico.zip](https://github.com/J-Siu/go-png2ico/files/11324433/test-256.ico.zip)
![test-256](https://user-images.githubusercontent.com/3171920/234333552-20861a2f-c798-48bd-b9bf-43338d2ca5cf.png)
[test-1200.ico.zip](https://github.com/J-Siu/go-png2ico/files/11324434/test-1200.ico.zip)
![test-1200](https://user-images.githubusercontent.com/3171920/234333556-1843b34e-fb26-488c-9f3f-aca1cd2bd6e0.png)

**Comment by J-Siu** [comment]
If both side are <= 256px, it works. For example, test-256.ico works, but not test-1200.ico.

**Comment by J-Siu** [comment]
I created a test page here: https://test.pin2me.dev/
The favicon.ico is working for both Chrome and Firefox.

**Comment by gedw99** [comment]
thanks for that. i must have screwed up the size. 

I will try again !!

**Comment by J-Siu** [comment]
@gedw99 Is it working?

**Comment by gedw99** [comment]
Hey @J-Siu 

it worked out in the end.

thsnks for asking !! Talk about 5 star customer support dude !!

**Comment by J-Siu** [comment]
@gedw99 Thx for quick reply, closing this now :D
